### ISSUE TITLE
Problem installation with conda

### ISSUE THREAD

**Issue by jfaraudo** [CompuCell3D/cc3d-player5#73]
**Unable to install with conda in Ubuntu**
The computer runs Ubuntu 20.04.6 LTS
For the installation we used:
conda install -c conda-forge -c compucell3d cc3d-player5

The output is shown below:

Channels:
 - conda-forge
 - compucell3d
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/nora/miniconda3/lib/python3.12/site-packages/urllib3/util/url.py", line 425, in parse_url
        host, port = _HOST_PORT_RE.match(host_port).groups()  # type: ignore[union-attr]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'groups'

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/home/nora/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 555, in send
        conn = self.get_connection_with_tls_context(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 398, in get_connection_with_tls_context
        proxy = prepend_scheme_if_needed(proxy, "http")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/requests/utils.py", line 995, in prepend_scheme_if_needed
        parsed = parse_url(url)
                 ^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/urllib3/util/url.py", line 451, in parse_url
        raise LocationParseError(source_url) from e
    urllib3.exceptions.LocationParseError: Failed to parse: https://proxy-address:port

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/nora/miniconda3/lib/python3.12/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/conda/cli/main.py", line 84, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/conda/cli/conda_argparse.py", line 200, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/conda/notices/core.py", line 132, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/conda/cli/main_install.py", line 152, in execute
        return install(args, parser, "install")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/conda/cli/install.py", line 377, in install
        unlink_link_transaction = solver.solve_for_transaction(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/conda/core/solve.py", line 153, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(
                                   ^^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/conda/core/solve.py", line 222, in solve_for_diff
        final_precs = self.solve_final_state(
                      ^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/conda_libmamba_solver/solver.py", line 207, in solve_final_state
        index = IndexHelper(
                ^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/conda_libmamba_solver/index.py", line 136, in __init__
        self._index = self._load_channels()
                      ^^^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/conda_libmamba_solver/index.py", line 332, in _load_channels
        jsons = {url: str(path) for (url, path) in executor.map(self._fetch_channel, urls)}
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
        yield _result_or_cancel(fs.pop())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
        return fut.result(timeout)
               ^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/concurrent/futures/_base.py", line 456, in result
        return self.__get_result()
               ^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
        raise self._exception
      File "/home/nora/miniconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/conda_libmamba_solver/index.py", line 254, in _fetch_channel
        json_path, _ = subdir_data.repo_fetch.fetch_latest_path()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/conda/gateways/repodata/__init__.py", line 749, in fetch_latest_path
        _, state = self.fetch_latest()
                   ^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/conda/gateways/repodata/__init__.py", line 847, in fetch_latest
        raw_repodata = repo.repodata_parsed(cache.state)  # type: ignore
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/conda/gateways/repodata/jlap/interface.py", line 87, in repodata_parsed
        repodata_json_or_none = fetch.request_url_jlap_state(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/conda/gateways/repodata/jlap/fetch.py", line 309, in request_url_jlap_state
        response = download_and_hash(
                   ^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/conda/gateways/repodata/jlap/fetch.py", line 243, in download_and_hash
        response = session.get(url, stream=True, timeout=timeout, headers=headers)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
        return self.request("GET", url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
        resp = self.send(prep, **send_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
        r = adapter.send(request, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/nora/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 559, in send
        raise InvalidURL(e, request=request)
    requests.exceptions.InvalidURL: Failed to parse: https://proxy-address:port

`$ /home/nora/miniconda3/bin/conda install -c conda-forge -c compucell3d cc3d-player5`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/nora/miniconda3/bin/conda
             CONDA_PREFIX=/home/nora/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/nora/miniconda3/bin/python
               CONDA_ROOT=/home/nora/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/home/nora/miniconda3/bin:/home/nora/miniconda3/condabin:/usr/local/sb
                          in:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/
                          games:/mnt/c/Program Files/Common Files/Oracle/Java/javapath:/mnt/c/Wi
                          ndows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Wind
                          ows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/m
                          nt/c/Program Files (x86)/NVIDIA
                          Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA
                          Corporation/NVIDIA NvDLISR:/mnt/c/Program
                          Files/Intel/WiFi/bin:/mnt/c/Program Files/Common Files/Intel/WirelessC
                          ommon:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/W
                          bem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/WINDOWS/Syst
                          em32/OpenSSH:/mnt/c/Users/norac/AppData/Local/Microsoft/WindowsApps:/s
                          nap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/nora/miniconda3
            shell level : 1
       user config file : /home/nora/.condarc
 populated config files : /home/nora/.condarc
          conda version : 24.5.0
    conda-build version : not installed
         python version : 3.12.4.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=broadwell
                          __conda=24.5.0=0
                          __glibc=2.31=0
                          __linux=4.4.0=0
                          __unix=0=0
       base environment : /home/nora/miniconda3  (writable)
      conda av data dir : /home/nora/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/compucell3d/linux-64
                          https://conda.anaconda.org/compucell3d/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/nora/miniconda3/pkgs
                          /home/nora/.conda/pkgs
       envs directories : /home/nora/miniconda3/envs
                          /home/nora/.conda/envs
               platform : linux-64
             user-agent : conda/24.5.0 requests/2.32.2 CPython/3.12.4 Linux/4.4.0-22621-Microsoft ubuntu/20.04.6 glibc/2.31 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8 aau/0.4.4 c/. s/. e/.
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: y
Upload did not complete.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

**Additional context**
The python version in anaconda in that computer is : 3.12.4.
Is that OK or should we change to python 3.10 ?

**Comment by jfaraudo** [comment]
The problem was the python version. We solved it creating an environment with pyton 3.10:
conda create -n py310 python=3.10
conda activate py310
conda install -c conda-forge -c compucell3d cc3d-player5
